spring.application.name=bookmyvenuebackend
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyvenue
spring.datasource.username=root
spring.datasource.password=\#Saviour99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true